CREATE TABLE Users(
	UserId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(), 
	FullName VARCHAR(150) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Password VARCHAR(MAX) NOT NULL
);

CREATE TABLE ExpenseCategories(
	ExpenseCategoryId INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(25) NOT NULL
);

CREATE TABLE Expenses(
	ExpenseId INT IDENTITY(1,1) PRIMARY KEY,
	Description VARCHAR(150) NOT NULL,
	Amount INT NOT NULL,
	Date DATE NOT NULL,
	Recurring BIT NOT NULL DEFAULT 0,
	UserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(UserId) NOT NULL,
	ExpenseCategoryId INT  FOREIGN KEY REFERENCES ExpenseCategories(ExpenseCategoryId) NOT NULL
);

CREATE TABLE Incomes(
	IncomeId INT IDENTITY(1,1) PRIMARY KEY,
	Source VARCHAR(150) NOT NULL,
	Amount INT NOT NULL,
	Date DATE NOT NULL,
	Monthly BIT NOT NULL DEFAULT 0,
	UserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(UserId) NOT NULL,
);

CREATE TABLE RefreshTokens(
	RefreshTokenId INT IDENTITY (1,1) PRIMARY KEY,
	Token VARCHAR(150) NOT NULL,
	ExpiryDate DATETIME NOT NULL,
	UserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(UserId) NOT NULL,
);